### ISSUE TITLE
Roadmap

### ISSUE THREAD

**Issue by PaperMonoid** [PaperMonoid/slinalg#1]
# Vector operations
- [x] Generation (zeros, random, fill)
- [x] Addition (Scalar, Vector)
- [x] Substraction (Scalar, Vector)
- [x] Multiplication (Scalar, Vector)
- [x] Division (Scalar, Vector)
- [x] Dot product
- [ ] Cross product
- [x] Norm 1
- [x] Norm 2
- [ ] Inner product
- [ ] Outer product
- [x] Discrete Fourier Transform
- [x] Inverse Discrete Fourier Transform
- [ ] Fast Fourier Transform
- [ ] Inverse Fast Fourier Transform
- [x] Sum
- [x] Min
- [x] Max
- [x] Product
- [x] Mean
- [x] Standard Deviation
- [ ] Sort

# Matrix operations
- [ ] Generation (zeros, random, fill, triangular)
- [ ] Addition (Scalar, Matrix)
- [ ] Substraction (Scalar, Matrix)
- [ ] Multiplication (Scalar, Matrix, Elementwise)
- [ ] Transposition
- [ ] Trace
- [ ] Dot product
- [ ] Inverse
- [ ] Pseudo inverse
- [ ] Determinant
- [ ] Inner product
- [ ] SVD
- [ ] Sum
- [ ] Min
- [ ] Max
- [ ] Product
- [ ] Mean
- [ ] Standard Deviation
- [ ] Sort

# Random Module
- [x] Uniform
- [x] Normal
